"use strict"
var game=new Phaser.Game(1366,768,Phaser.AUTO,"",null,!1,!1),MainState=function(){}
MainState.prototype={worldLength:40,tileSize:32,xOffset:43,yPosition:352,paddlePosition:0,ballPosition:19,ballVelocity:-.5,blockAmount:4,paddleSprite:void 0,ballSprite:void 0,blockSprites:void 0,scoreText:void 0,score:0,gameOver:!1,blopp1SFX:void 0,blopp2SFX:void 0,gameoverSFX:void 0,preload:function(){game.load.image("paddle","assets/sprites/paddle.png"),game.load.image("ball","assets/sprites/ball.png"),game.load.image("block0","assets/sprites/block1.png"),game.load.image("block1","assets/sprites/block2.png"),game.load.image("block2","assets/sprites/block3.png"),game.load.image("block3","assets/sprites/block4.png"),game.load.image("bg","assets/sprites/bg.png"),game.load.audio("blopp1","assets/sfx/blopp2.wav"),game.load.audio("blopp2","assets/sfx/blopp1.wav"),game.load.audio("gameover","assets/sfx/gameover.wav"),this.blockSprites=game.add.group(),game.load.script("utilScript","../js/util.js"),game.load.script("directionEnumScript","../js/direction.enum.js"),game.load.script("keycodesScript","../js/keycodes.js"),game.add.text(0,0,"",{font:"56px pixelbug",fill:"#ffffff"})},create:function(){game.add.sprite(0,0,"bg"),game.stage.backgroundColor="#FFFFFF",game.scale.pageAlignHorizontally=!0,game.scale.pageAlignVertically=!0
var e=this.tileSize/8
this.blopp1SFX=game.add.audio("blopp1"),this.blopp2SFX=game.add.audio("blopp2"),this.gameoverSFX=game.add.audio("gameover"),this.paddleSprite=game.add.sprite(this.paddlePosition*this.tileSize+this.xOffset,this.yPosition,"paddle"),this.paddleSprite.scale.set(e,e),this.ballSprite=game.add.sprite(this.ballPosition*this.tileSize+this.xOffset,this.yPosition,"ball"),this.ballSprite.scale.set(e,e)
for(var t=0;t<this.blockAmount;++t){var i=this.worldLength-1-t,s=this.blockSprites.create(i*this.tileSize+this.xOffset,this.yPosition,"block"+t)
s.scale.set(e,e),s.tilePosition=i}var a=this
game.input.keyboard.onDownCallback=function(e){keycodes.restart.includes(e.key)&&(a.ballPosition=19,a.ballVelocity=-.5,a.score=0,a.scoreText.text="Score: "+a.score,a.scoreText.visible=!0,a.gameOver=!1,game.stage.backgroundColor="#FFFFFF",game.state.start("MainState"))},this.scoreText=game.add.text(this.xOffset,0,"Score: 0",{font:"56px pixelbug",fill:"#ffffff"})},update:function(){if(!this.gameOver)if(this.ballPosition+=this.ballVelocity,this.ballSprite.position.x=this.ballPosition*this.tileSize+this.xOffset,0==this.blockSprites.children.length){var e=150
this.scoreText.visible=!1
var t=game.add.text(game.world.width/2,e,"YOU WIN!",{font:"56px pixelbug",fill:"#ffffff"}),i=game.add.text(game.world.width/2,e+80,"High score: "+this.score,{font:"48px pixelbug",fill:"#ffffff"}),s=game.add.text(game.world.width/2,e+160,"Your score: "+this.score,{font:"48px pixelbug",fill:"#ffffff"})
util.recentreText(t),util.recentreText(s),util.recentreText(i),this.gameOver=!0,this.gameoverSFX.play()}else this.ballPosition<=this.paddlePosition+1?(this.ballVelocity*=-1,this.blopp1SFX.play()):this.ballPosition>=this.getLastBlock().tilePosition-1&&(this.ballVelocity*=-1,this.score++,this.scoreText.text="Score: "+this.score,this.blopp2SFX.play(),this.getLastBlock().destroy())},getLastBlock:function(){var e=this.blockSprites.children.length-1
return this.blockSprites.children[e]}},game.state.add("MainState",MainState),game.state.start("MainState")
